/*
Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        // similar to 136. Single Number - https://leetcode.com/problems/single-number/
        char ans='\0';
        // use XOR to find the difference
        for(char c:s+t) ans ^= c;
        return ans;
    }
};

class Solution2 {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> m;
        char ans;
        for(int i=0;i<t.size();i++) m[t[i]-'a']++;
        for(int i=0;i<s.size();i++) m[s[i]-'a']--;
        for(int i=0;i<26;i++) {
            if(m[i]==1){
                ans=i+'a';
                break;
            }
        }
        return ans;
    }
};

static const auto io_sync_off = []() {std::ios::sync_with_stdio(false);cin.tie(nullptr);cout.tie(nullptr);return 0;}();